### PR TITLE
added missing line to patchlevel.h.in and changed checks for HAVE_GET…

### PR DESCRIPTION
**Pull request by Shea690901**
…PAGESIZE and HAVE_SYSCONF

### CODE REVIEW

**Comment by Shea690901** [comment]
smalloc.c won't compile (on my device only?) with previuos method of checking for defined/undefined macros
patchlevel.h (or some other, more appropriate file?) was missing some value for PACKAGE_URL

**Comment by zesstra** [comment]
Mhmmm. On my machine PACKAGE_URL is defined by machine.h which is automagically by autoconf. Did you execute ./autogen.sh before configure?

And if I am not very much mistaken, the defined() syntax is allowed by C99. So I am surprised. Would you tell us about your build environment, especially compiler version and autoconf version?

**Comment by Shea690901** [comment]
'cctools' that's an Android-app using gcc 4.8
Give me much trouble :(
I got everything compiled but none(!) of the testss succeeds:
#include …
won't work.
I'm now trying to compile my own toolchain and hope to solve my problems this way.
Although it probably won't absolve me of my forgetfulnes (nope, didn't run autogen.sh)

**Comment by zesstra** [comment]
Ouch, I am surprised that it was possible to configure and compile it without autogen.sh. This is really essential when using non-released code. It may explain some of your troubles.

However, I guess that there will be some changes necessary until it works on ARM & Co. Gnomi and me don't pursue this actively, but if somebody wants to work on this we are open for contributions if they match our codestyle. ;-)

**Comment by zesstra** [comment]
I changed the two defines in slaballoc.c and smalloc.c but otherwise I am closing this for now. If you have patches for improving portability, please open another pull request.

**Pull request closed without merging**
