### PR TITLE
lex: support reading numeric literals with separator.

### PR DESCRIPTION
**Pull request by cpu**
This pull request introduces support for reading/lexing numeric LPC literals that contain semantically ignored separators for enhanced readability. We follow the C++14 standard and use a single quote (`'`) as the separator character.

Writing a numeric literal like `int x = 10000000;` makes it hard for a human to immediately recognize the order of magnitude of the number. As of this pull request the same literal can be written `int x = 10'000'000;` which is much faster to recognize as ten million. This same feature is also made available in the binary, octal and hex literal notations (`0b1101'1001`, `0o777'777`, `0xFF'FF`).

This brings a popular feature from many other languages (Python, C#, Java, Perl, Ruby, Rust, etc) to LPC. Similar to the Python [PEP-0515](https://peps.python.org/pep-0515/) and C++ implementations we do not allow leading separators, or more than one separator. E.g. `'1000` or `1''00` are invalid syntax.

### CODE REVIEW

**Comment by cpu** [comment]
Based on discussion in the #ldmud channel of the LPC discord I've switched this PR to follow the C++14 standard and use `'` for the separator instead of `_` on the assumption C will likely adopt this choice too.

One final "gotcha" to consider: this implementation allows trailing `'`, like `int x = 10';` - I'll look at fixing this but suspect it might make the implementation more complicated and deviate further from the original code in `lex.c`.

**Comment by cpu** [comment]
> One final "gotcha" to consider: this implementation allows trailing ', like int x = 10'; - I'll look at fixing this but suspect it might make the implementation more complicated and deviate further from the original code in lex.c.

I fixed this (and a problem with leading invalid `'` separators) in 756c566d2ef4bb4f85e41b2291714fdd882bbe35 I think this should be ready for review/consideration now! :stars:

**Comment by zesstra** [comment]
Mhmm. I don't really like this feature. Especially using the '  because that has signifance in code: starting literals and in the operator #'.

But I am also not quite convinced in the first place that is hugely useful because it introduces another special meaning to a single character that humans need to recognize and remember. I personally feel that this offets any small effect on readability in rare circumstances (large numerical constants are are rare in code...). Especially since people now have to think about the meaning of numerical constants separated by some character. And e.g. 1'2'3'4'5 is not really readable.

**Comment by cpu** [comment]
> I don't really like this feature. Especially using the ' because that has signifance in code: starting literals and in the operator #'.

Personally I liked it more using `_` as the separator, like in Python, but went with `'` to match C++ at @amotzkau's recommendation.

> large numerical constants are are rare in code...

As one counter example a lib that I contribute to has had a lot of "number creep" over time (_for better or worse_ :skull_and_crossbones: ) such that players are routinely earning millions and billions of various things (exp. primarily). Being able to represent those literals clearly is helpful to me in these situations.

In general I hear your concerns about readability. For some reassurance we could look at something like [Rosetta Code](https://rosettacode.org/wiki/Rosetta_Code) where there's a page dedicated to comparing languages that have [implemented numeric separator syntax already](https://rosettacode.org/wiki/Numeric_separator_syntax). There's a diverse set represented there including many popular options (e.g. Python, Go, Java, C++, C#, Perl, Ada, Ruby, Scala). Those languages seldom agree on much but they do all have a way to express literals with a separator for readability which I think is a vote in favour.

All that said, I don't want to bother folks with a long prolonged debate about something like this :-) If you and Gnomi are both :-1: we can close this out. I won't make any more impassioned arguments for or against. 

Thanks for giving your input!

**Comment by zesstra** [comment]
Maybe Morgengrauen is special, but I asked around the programmers and could not find people who find it important, but several who did not like it and some were indifferent.
Some people said, they already have difficulty to parse the usual thousands separator (made worse because they are different in german and english) and find something like 1000'000 actually confusing and do not think of it as a number etc.
I also have concerns with respect to screenreaders for visually impaired people who will pronounce numbers, but not constructs with arbitrary thousands separators.

One sentiment was, it is something for editors to change visual representation of code if needed and more (individual) output representations in sprintf() & Co would be useful or to be able to configure it for a specific connection.

One wish instead was to support notations like 1e6 for ints/numbers.

**Pull request closed without merging**
