### PR TITLE
Remove generated files and add .gitignore for src directories

### PR DESCRIPTION
**Pull request by ktiedt**
Not sure if anyone else really cares about this since it has gone this long without but... I am looking to do a bit of work on things locally and preventing all generated files from showing up in my git status was a major help in keeping things more organized.

This currently allows for: ./autogen.sh && ./configure && make - without cluttering git status at least on Ubuntu 14.04 currently.

### CODE REVIEW

**Comment by zesstra** [comment]
Well...
At least some of these generated files are included deliberately. As I described in Pullrequest #9:
The presence of files like configure, patchlevel.h, machine.h.in is intended to enable people without working autoconf, git  & Co to compile the driver. We update these files from time to time and at least once when a release is tagged. Therefore I am not so sure about removing it.

However, ignoring the executables, .o , .log, .status etc. should be a good thing.
Would you be willing to separate your patch?

**Comment by ktiedt** [comment]
Sure, I redo it to leave those files, for the sake of the pull request, I'll just include them in mine after the fact then to avoid them coming up as modified in my own setup. I'll do that later today. Thanks for the feedback!

**Comment by zesstra** [comment]
Thank you for contributing, that is always welcome and motivating!

**Comment by ktiedt** [comment]
@zesstra Files returned and .gitignore updated, I do disagree with leaving those files intact, at least in that directory, since it prevents ever ignoring them without causing changes, but - If not having autoconf is something so many people can't overcome (is this really a problem that people can't resolve?), I can see why it might be done that way

**Comment by ktiedt** [comment]
Hmmm looking into what the conflicts are now, it didnt say there were any yesterday.

**Comment by ktiedt** [comment]
Well it seems like you just copied the pull request instead of actually using it, guess I will close this.

**Comment by zesstra** [comment]
Not exactly. I rebased it to remove the two commits removing and re-adding the files to keep the history clean. Also, I squashed the commits changing .gitignore and added a few more file patterns to ignore.

**Pull request closed without merging**
